name: Auto Assign Assignees(bot)

on:
  issues:
    types: [opened, edited]
    
jobs:
  assign_assignee:
    name: Assign Assignees
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.repo.owner]
            })
