name: Auto Pull Request Checks(bot)

on:
  pull_request:
    branches:
      - master
      - main
      - dev

jobs:
  pull_request_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Test
        run: |
          dotnet test test/UnitTest -c Release --collect:"XPlat Code Coverage"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
