name: auto sync issue to PR(bot)

on:
  pull_request:
    types: [opened, edited]

jobs:
  sync_assignees:
    name: sync assignees
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.pull_request.body
            const matches = body.match(/#(\d+)/)
            if (!matches || matches.length <= 1) {
                console.log('this PR has no related issue!')
            }
            else {
                const related_issue_number = matches[1]
                const issue = await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: related_issue_number
                })
                if (issue.data.length == 0 || issue.data.assignees.length == 0) {
                  console.log(`there no assignees on issue \#${related_issue_number}`)
                }
                else {
                  const assignees = issue.data.assignees.map(v => v.login)
                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    assignees: assignees
                  })
                  console.log('sync assignees', assignees)
                }
            }

  sync_labels:
    name: sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.pull_request.body
            const matches = body.match(/#(\d+)/)
            if (!matches || matches.length <= 1) {
              console.log('this PR has no related issue!')
            }
            else {
              const related_issue_number = matches[1]
              const labels = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: related_issue_number
              })
              if(labels.data.length == 0) {
                console.log(`there no labels on issue #${related_issue_number}`)
              }
              else {
                const issue_labels = labels.data.map(v => v.name)
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: issue_labels
                })
                console.log('sync labels', issue_labels)
              }
            }

  sync_milestone:
    name: sync milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.pull_request.body
            const matches = body.match(/#(\d+)/)
            if (!matches || matches.length <= 1) {
              console.log('this PR has no related issue!')
            }
            else {
              const related_issue_number = matches[1]
              const issue = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: related_issue_number
              })
              if (issue.data.length == 0 || issue.data.milestone == null) {
                console.log(`there no milestone on issue \#${related_issue_number}`)
              }
              else {
                const milestone = issue.data.milestone
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  milestone: milestone.number
                })
                console.log(`sync milestone ${milestone.title}`)
              }
            }
