name: auto assign issue(bot)

on:
  issues:
    types: [opened, edited]
    
jobs:
  assign_assignee:
    name: assign assignees
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: ArgoZhang
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const repo_owner = process.env.REPO_OWNER
            const current_assignees = context.payload.issue.assignees.map(v => v.login)
            if (current_assignees.indexOf(repo_owner) > -1) {
              console.log(`skip assign assignees action. current assignees`, current_assignees)
            }
            else {
              current_assignees.push(repo_owner)
              github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: current_assignees
              })
            }
  assign_label:
    name: assign label
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        not-before: 2023-01-25T00:00:00Z
        enable-versioned-regex: 0
        include-title: 1

  assign_miletone:
    name: assign milestone
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            if (milestones.data.length > 0) {
              const milestone = milestones.data.pop()
              github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                milestone: milestone.number
              })
            }
