name: Sync Labels(bot)

on:
  pull_request:
    types: [opened, edited]

jobs:
  sync_labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = context.payload.pull_request.body
            const matches = body.match(/#(\d+)/)
            if (!matches || matches.length <= 1) {
              console.log('This PR has no related issue!')
            }
            else {
              const related_issue_number = matches[1]
              const labels = await github.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: related_issue_number
              })
              if(labels.data.length == 0) {
                console.log(`There no labels on issue #${related_issue_number}`)
              }
              else {
                const issue_labels = labels.data.map(v => v.name)
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: issue_labels
                })
                console.log('Sync labels', issue_labels)
              }
            }
